# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'http://git.jollycorp.com:8088/frontend-ios/JollySpecs.git'
platform :ios, '8.0'

target 'SnapChatAppDemo' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for SnapChatAppDemo
    # pod 'SnapSDK', :subspecs => ['SCSDKLoginKit']
    # pod 'Protobuf'
    # pod 'SnapSDK'
    pod 'MJRefresh'
    target 'SnapChatAppDemoTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'SnapChatAppDemoUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
